apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app1
  labels:
    app: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo-app
        image: nikitanand/demo
        ports:
        - containerPort: 80

